In [1]:
import numpy as np
from Genotype import *

In [12]:
# Data is set to all color 0 on all layers
data = [np.zeros((3, 3, 3)) for i in range(4)]

# If grid is targeting layer 0 if all color 0
dna = np.zeros((1, 14)).astype(int)
dna[0,1:10] = 1

g = Genotype(data=data,
             dna=dna)

g.data[0]

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [13]:
g.update()

In [14]:
g.data[0]

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [15]:
dna

array([[0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0]])

In [69]:
a = np.array([1,1,1,1,1,1,1,1,0]).reshape(3,3)

# Look at top-left
np.roll(a,shift=(1,1),axis=(0,1))

# Look at top
np.roll(a,shift=(1,0),axis=(0,1))

# Look at top-right
np.roll(a,shift=(1,-1),axis=(0,1))

# Look at left
np.roll(a,shift=(0,1),axis=(0,1))

# Look at center
np.roll(a,shift=(0,0),axis=(0,1))

# Look at right
np.roll(a,shift=(0,-1),axis=(0,1))

# Look at bottom-left
np.roll(a,shift=(-1,1),axis=(0,1))

# Look at bottom
np.roll(a,shift=(-1,0),axis=(0,1))

# Look at bottom-right
np.roll(a,shift=(-1,-1),axis=(0,1))

array([[1, 1, 1],
       [1, 0, 1],
       [1, 1, 1]])